use crate::types::*;

const ROM_BANK0_START_ADDRESS: usize = 0x0000;
const ROM_BANK1_START_ADDRESS: usize = 0x4000;
const VRAM_START_ADDRESS: usize = 0x8000;
const EXTERNAL_RAM_START_ADDRESS: usize = 0xA000;
/// Work RAM
const WRAM_BANK0_START_ADDRESS: usize = 0xC000;
/// Work RAM Bank 1-7
const WRAM_BANK1_START_ADDRESS: usize = 0xD000;
/// 
const ECHO_RAM_START_ADDRESS: usize = 0xE000;
/// Object Attribute Memory (OAM)
const OAM_START_ADDRESS: usize = 0xFE00;
const NOT_USABLE_START_ADDRESS: usize = 0xFEA0;
/// 
const IOREG_START_ADDRESS: usize = 0xFF00;
/// High RAM (HRAM)
const HRAM_START_ADDRESS: usize = 0xFF80;
/// Intterupt Enable Register
const IE_START_ADDRESS: usize = 0xFFFF;

const IOREG_NR10_CHANNEL1_SWEEP: usize = 0xFF10;
const IOREG_NR11_CHANNEL1_LENGTH_TIMER_DURY_CYCLE: usize = 0xFF11;
const IOREG_NR12_CHANNEL1_VOLUME_ENVELOPE: usize = 0xFF12;
const IOREG_NR13_CHANNEL1_PERIOD_LOW: usize = 0xFF13;
const IOREG_NR14_CHANNEL1_PERIOD_HIGH_CONTROL: usize = 0xFF14;
const IOREG_NR21_CHANNEL2_LENGTH_TIMER_DURY_CYCLE: usize = 0xFF16;
const IOREG_NR22_CHANNEL2_VOLUME_ENVELOPE: usize = 0xFF17;
const IOREG_NR23_CHANNEL2_PERIOD_LOW: usize = 0xFF18;
const IOREG_NR24_CHANNEL2_PERIOD_HIGH_CONTROL: usize = 0xFF19;
const IOREG_NR30_CHANNEL3_DAC_ENABLE: usize = 0xFF1A;
const IOREG_NR31_CHANNEL3_LENGTH_TIMER: usize = 0xFF1B;
const IOREG_NR32_CHANNEL3_OUTPUT_LEVEL: usize = 0xFF1C;
const IOREG_NR33_CHANNEL3_PERIOD_LOW: usize = 0xFF1D;
const IOREG_NR33_CHANNEL3_PERIOD_HIGH_CONTROL: usize = 0xFF1E;
const IOREG_NR41_CHANNEL4_LENGTH_TIMER: usize = 0xFF20;
const IOREG_NR42_CHANNEL4_VOLUME_ENVELOPE: usize = 0xFF21;
const IOREG_NR43_CHANNEL4_FREQUENCY_RANDOMNESS: usize = 0xFF22;
const IOREG_NR44_CHANNEL4_CONTROL: usize = 0xFF23;
const IOREG_NR51_MASTER_VOLUME_VIN_PANNING: usize = 0xFF24;
const IOREG_NR51_SOUND_PANNING: usize = 0xFF25;
const IOREG_NR52_AUDIO_MASTER_CONTROL: usize = 0xFF26;
const IOREG_CHANNEL3_WAVE_PATTERN_RAM_START: usize = 0xFF30;

/// SM83エミュレータ
pub struct SM83
{
    /// レジスタ
    reg: SM83Registers,
    /// 64KBメモリ領域
    mem: [u8; 65536],
}
